Use Clang 11 again
We actually *should* try to use the newest clang; I'm probably going to have to fix that issue in dyld that caused it to die:
```
/home/circleci/project/src/dyld/dyld3/MachOAnalyzer.cpp:3319:24: error: cannot initialize return object of type 'bool' with an rvalue of type 'nullptr_t'
                return nullptr;
```